apiVersion: v1
kind: Service
metadata:
  labels:
    db: pgadmin
  name: pgadmin-service
spec:
  ports:
  - nodePort: 30165
    port: 80
    targetPort: 80
  selector:
    db: pgadmin
  type: NodePort