apiVersion: v1
kind: Service
metadata:
  labels:
    db: pgadmin
  name: pgadmin-service
spec:
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 30165
  selector:
    db: pgadmin
  type: ClusterIP